# .github/workflows/main.yml
name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load variables
        id: load-variables
        run: |
          echo "VAR1=$(cat .github/variables.yml | jq -r '.VAR1')" >> $GITHUB_ENV
          echo "VAR2=$(cat .github/variables.yml | jq -r '.VAR2')" >> $GITHUB_ENV

      - name: Read variables
        run: |
          echo $VAR1
          echo $VAR2
