# .github/workflows/main.yml
name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt update -y
          sudo apt install yq -y

      - name: Load variables
        id: load-variables
        run: |
          echo "VAR1=$(yq -r '.VAR1' .github/variables.yml)" >> $GITHUB_ENV
          echo "VAR2=$(yq -r '.VAR2' .github/variables.yml)" >> $GITHUB_ENV

      - name: Read variables
        run: |
          echo $VAR1
          echo $VAR2
