# .github/workflows/main.yml
name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load variables
        run: |
          echo "${{ env.VARIABLES_YAML }}" > .github/variables.yml

      - name: Read variables
        run: |
          echo "${{ env.VARIABLES_YAML }}"
          echo "${{ fromYaml(env.VARIABLES_YAML).VAR1 }}"
          echo "${{ fromYaml(env.VARIABLES_YAML).VAR2 }}"
