# .github/workflows/main.yml
name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load variables
        id: load-variables
        run: |
          echo "::set-output name=variables::$(cat .github/variables.yml | jq -r tostring)"

      - name: Read variables
        run: |
          echo "${{ steps.load-variables.outputs.variables }}" | jq -r '.VAR1'
          echo "${{ steps.load-variables.outputs.variables }}" | jq -r '.VAR2'
