# .github/workflows/main.yml
name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load variables
        id: load-variables
        uses: azure/github-actions/yaml-parser@master
        with:
          file: .github/variables.yml

      - name: Read variables
        run: |
          echo ${{ steps.load-variables.outputs.VAR1 }}
          echo ${{ steps.load-variables.outputs.VAR2 }}
